version: '3.8'

services:
  mapin-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
